### ISSUE TITLE
LOVE the idea of this plugin! 

### ISSUE THREAD

**Issue by musesupplyco** [ryderdamen/WP-Conversation-Viewer#2]
Seems to need some tweaking with the new Gutenburg interface?  Works if the entire conversation is wrapped only in <p></p>...  otherwise, all goes wonky.

**Comment by ryderdamen** [comment]
@musesupplyco Thanks! I haven't yet gotten around to testing it with Gutenburg, but it's on my list of things to do in the next few weeks. I'll keep this ticket open as a reminder.

**Comment by ryderdamen** [comment]
Hey @musesupplyco, thanks for the heads up. I finally got some free time to get around to looking into this.

It looks like the bug here is when short-code is pasted directly into the editor. When that happens, it defaults to pre-formatted / standard code.

When the specific "shortcode" block is selected, and the text is pasted in, it seems to work as expected. See the images below for clarification.

<img width="704" alt="screen shot 2019-01-31 at 9 50 19 pm" src="https://user-images.githubusercontent.com/26048365/52099755-7fc41f80-25a2-11e9-96fc-32dbe2c35bbb.png">
<img width="811" alt="screen shot 2019-01-31 at 9 50 25 pm" src="https://user-images.githubusercontent.com/26048365/52099759-8357a680-25a2-11e9-89fb-b71eb95af95a.png">


If this wasn't the problem you were referring to, let me know and I'll reopen this and look a bit further. Thanks so much!
